#!/bin/bash

##########################
#
# My personal bashrc stuff:
#  Best to call from ~./bashrc as follows:
#
#      if [ -f ~/.mybashrc ] ; then
#          . ~/.mybashrc
#      fi
#
# A dummy variable to test if this script has been executed
MYBASHRC=YES
##########################


######### Aliases

alias emacs="emacs -nw"
alias restartwifi="wpa_cli -i wlan0 reconfigure"
alias ll="ls -al"

# git
alias gita="git add"
alias gitc="git commit -a"
alias gitd="git diff"
alias gitp="git push"
alias gits="git status"
alias gitl="git log --oneline --graph --decorate"

alias sshagent="eval `ssh-agent -s`"
